### ISSUE TITLE
Infografía Realidad Aumentada_Edwin Bautista García

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/infografia-Edwin-1012#1]
[Infografía Realidad Aumentada_Edwin Bautista García.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Edwin-1012/files/8054398/Infografia.Realidad.Aumentada_Edwin.Bautista.Garcia.pdf)

**Comment by Graciela2102** [comment]
Buen trabajo, la infografia contiene todos los datos necesarios para el mejor entendimiento del tema. información organizada y buen diseño.
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
