### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/infografia-Edwin-1012#2]
![Infografia Ingenieria de Requisitos_Edwin Bautista García](https://user-images.githubusercontent.com/72049201/109897647-a3ae2f80-7c58-11eb-8bb3-df30c883f38e.jpg)

**Comment by Nancy2050** [comment]
Calificación: 20%

Evaluó: Nancy Velasco Santiago

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
